<?php

/**
 * @file
 * Provides a minimal wrapper around the Mirador Viewer.
 */

// Shorthand for referencing the Mirador library.
define('ISLANDORA_MIRADOR_LIB', 'mirador');

/**
 * Implements hook_menu().
 */
function islandora_mirador_menu() {
  return array(
    // Stand alone viewer rendered in it's own page.
    'mirador/demo' => array(
      'title' => 'Mirador Demo',
      'page callback' => 'islandora_mirador_demo_menu_item',
      'file' => 'includes/callbacks.inc',
      'type' => MENU_NORMAL_ITEM,
      'access callback' => TRUE,
    ),
    // iFrame.
    'mirador' => array(
      'page callback' => 'islandora_mirador_iframe_callback',
      'file' => 'includes/callbacks.inc',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_mirador_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_mirador_viewer' => array(
      'file' => 'theme/theme.inc',
      'variables' => array(
        'settings' => array(),
      ),
    ),
    'islandora_mirador_viewer_iframe' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-mirador-viewer-iframe',
      'render element' => 'page',
      'variables' => array(
        'settings' => array(),
      ),
    ),
    'islandora_mirador_viewer_embedded' => array(
      'file' => 'theme/theme.inc',
      'variables' => array(
        'src' => url('mirador'),
        'width' => '100%',
        'height' => '800px',
      ),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function islandora_mirador_libraries_info() {
  return array(
    'mirador' => array(
      'name' => ISLANDORA_MIRADOR_LIB,
      'vendor url' => 'http://projectmirador.org/',
      'download url' => 'https://github.com/IIIF/mirador',
      'version arguments' => array(
        'file' => 'bower.json',
        'pattern' => '/"version": "([0-9.]+)"/',
        'lines' => 200,
      ),
      'files' => array(
        'js' => array(
          'build/mirador/mirador.js',
        ),
        'css' => array(
          'build/mirador/css/mirador-combined.min.css',
        ),
      ),
    ),
  );
}
