<?php

/**
 * Implements hook_menu().
 */
function islandora_wellcome_menu() {
  $items = array();
  $items['islandora_wellcome/view'] = array(
      'title' => 'Islandora Wellcome Viewer',
      'page callback' => 'islandora_wellcome_viewer',
      'access arguments' => array(TRUE),
      'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora_wellcome/data_uri'] = array(
    'title' => 'Islandora Wellcome Viewer tits',
    'page callback' => 'islandora_wellcome_viewer_data_uri',
    'access arguments' => array(TRUE),
    'type' => MENU_NORMAL_ITEM,
  );
  // TODO: This menu path is to provide dzi tile information
//   $items['islandora_wellcome/dzi/%islandora_object/%obj_page'] = array(
//   		'title' => 'Islandora Wellcome Viewer',
//   		'page callback' => 'islandora_wellcome_viewer_dzi_uri',
//   		'page arguments' => array(2,3),
//   		'access callback' => 'islandora_object_access',
//     	'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
//   		'type' => MENU_NORMAL_ITEM,
//   );
  
  $items['islandora_wellcome/dzi/%islandora_object'] = array(
  		'title' => 'Islandora Wellcome Viewer',
  		'page callback' => 'islandora_wellcome_viewer_dzi_uri',
  		'page arguments' => array(2),
  		'type' => MENU_NORMAL_ITEM,
  		'access callback' => 'islandora_object_access_callback',
  		'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
  );
  return $items;
}

/**
 * Object entry point.
 *
 * @param AbstractObject $fedora_object
 *   The fedora object being viewed.
 */
function islandora_wellcome_viewer_dzi_uri($fedora_object) {
  
}

/**
 * Implements hook_theme().
 */
function islandora_wellcome_theme($existing, $type, $theme, $path) {
	dsm(array(), "hit theme");
  return array(
    'islandora_wellcome_viewer' => array(
      'template' => 'theme/islandora-wellcome-viewer',
      'variables' => array(
        'object' => NULL,
        'path' => NULL,
        'base_path' => NULL,
      ),
    ),
  );
}

/**
 * Drupal menu callback..
 */
function islandora_wellcome_viewer() {
  global $base_url;
  dsm(array(), "hit theme");
  $module_path = drupal_get_path('module', 'islandora_wellcome');
  return theme('islandora_wellcome_viewer', array(
    'object' => NULL,
    'path' => $module_path,
    'base_path' => $base_url,
    )
  );
}

/**
 * Implements hook_preprocess().
 */
function islandora_wellcome_preprocess_islandora_wellcome_viewer(&$variables) {
  // TODO: after moving processed images/dzi info into temp, check if they exist before generating
  // new tile/dzi information. It is being generated every time now.
  $cache = exec("vips dzsave /var/www/drupal7/sites/all/modules/islandora_wellcome/CCITT_1.TIF /var/www/drupal7/sites/all/modules/islandora_wellcome/my_dz_dir");
  $variables['cache'] = $cache;
}

/**
 * Return JSON data representing this book.
 */
function islandora_wellcome_viewer_data_uri() {
  $test_pid = "islandora:38";
  global $base_url;

  $fedora_object = islandora_object_load($test_pid);

  $uri_data = array();
  $module_path = drupal_get_path('module', 'islandora_wellcome');
  // TODO: set defaults, move to utils.
  $uri_data['extensions'] = array(
    "isAllOpen" => true,
    "parsed" => "/Date(1392306369478+0000)/",
    "defaultToFirstDip" => false,
  );
  $uri_data['identifier'] = "b16136330";
  // TODO: package mods/parameters from ds/admin menu.
  $uri_data['assetSequences'] = array(array(
    "extensions" => array(
      "dzLicenseCode" => "J",
      "isAllOpen" => true,
      "permittedOperations" => "",
      "isMultipleManifestation" => false,
      "volumeNumber" => -1,
      "copyNumber" => 1,
    ),
    "packageIdentifier" => "b16136330",
    "index" => 0,
    "assetType" => "seadragon/dzi",
    "assetCount" => 0,
    "supportsSearch" => TRUE,
    "autoCompletePath" => "/service/autocomplete/b16136330/0",
    "rootSection" => array(
      "extensions" => array(
        "accessCondition" => "Open",
        "authStatus" => "Allowed",
        "mods" => array(
          "title" => "[\"DNA\"]",
          "classification" => "Digitised",
          "language" => "d",
          "originDateDisplay" => "[c. 1953]",
          "originPlace" => "Wellcome Trust",
          "originPublisher" => "Wellcome Trust",
          "physicalDescription" => "reformatted digital",
          "recordIdentifier" => "b16136330",
          "names" => array(),
          "accessCondition" => "Open",
          "dzLicenseCode" => "J",
          "leader6" => "t",
          "wellcomeIdentifier" => "can be viewed on the Wellcome Images website.",
          "repositoryName" => "Wellcome Library;",
          "volumeNumber" => -1,
          "copyNumber" => 1
        ),
      ),
      "title" => "[\"DNA\"]",
      "sectionType" => "Archive",
      "assets" => array(0,1),
    ),
    "assets" => array(
      array(
        "extensions" => array(),
        "identifier" => "islandora%3A38",
        "order" => 1,
        "orderLabel" => " - ",
        "width" => 2643,
        "height" => 3965,
        "dziUri" => "/islandora_wellcome/dzi/$fedora_object->id/page_1/",
        "navigatorPath" => "/islandora/object/$fedora_object->id/datastream/TN/view",
        "thumbnailPath" => "/islandora/object/$fedora_object->id/datastream/TN/view"
      ),
      array(
        "extensions" => array(), 
        "identifier" => "islandora%3A31", 
        "order" => 2, 
        "orderLabel" => " - ", 
        "width" => 2643, 
        "height" => 3965, 
        "dziUri" => "/islandora_wellcome/dzi/$fedora_object->id/page_2/",
        "navigatorPath" => "/islandora/object/$fedora_object->id/datastream/TN/view", 
        "thumbnailPath" => "/islandora/object/$fedora_object->id/datastream/TN/view"
      )
    ),
  ));
  // TODO: Populate from utilities.
  $uri_data['bibliographicInformation'] = "/biblio/b16136330";

  return drupal_json_output($uri_data);
  exit();
}